### ISSUE TITLE
Support for tracking commits pushed directly to branch

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#373]
## Problem

In certain cases, contributions are made to a project by pushing a commit to a branch. Leaderboard currently does not track such activities performed by the contributor.

<img width="851" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/601a1d1e-be61-4f71-ae8d-c3f081e8b563">

## Action Items

- [ ] Update scraper to track commits pushed to a branch by a contributor. Tag those activities if it was made to the default branch or not.
- [ ] Update the contributor page to reflect the new information being captured.

**Comment by dgparmar14** [comment]
I want to work on this issue.

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/d39e8c1d-24e9-4df9-b796-fb51e489c76d)


@rithviknishad  Please review the logic and the method used to fetch the default branch name in the provided code snippet.

**Comment by rithviknishad** [comment]
Do events show `PushEvent`s of fork branches? 

If not, I don't think this will be a great value addition since most of the contributions are from fork branches.

**Comment by dgparmar14** [comment]
Okay, So I need to track also a commits from contributors forked repositories and also show them in profile page, right ?

**Comment by rithviknishad** [comment]
Yeah, but is it possible?

**Comment by dgparmar14** [comment]
Yup, It's possible
Here are the steps

1. Fetch your main repository: First,  fetch information about the main repository.
2. Fetch the forks of the main repository
3. Iterate through forks: For each fork, you'll fetch the commits made by the contributors in their forked repositories.

![Screenshot 2024-03-22 191640](https://github.com/coronasafe/leaderboard/assets/99136186/34bde2ef-cb79-4e2c-864c-e1bbee217695)
![Screenshot 2024-03-22 191651](https://github.com/coronasafe/leaderboard/assets/99136186/b9b0c527-8537-4c8d-b571-cf71f8ffde90)


We can create these two functions or one by merging these two and call this from  scrapper function.

**Comment by dgparmar14** [comment]
@rithviknishad Even if we utilize the `GraphQL API`, we still encounter the same issue. We'd need to initially retrieve all repositories and their associated forks before we can access their commits. While pagination can help mitigate rate limit problems, it may not be applicable in this scenario since we're scraping data.

**Comment by rithviknishad** [comment]
Yeah that'd be nice. That'd also bring ability to blend viewing of scrapped data with data from other sources

**Comment by rajku-dev** [comment]
Currently, the feed page only shows push activities for the core team with direct access. The issue is to display all commits for made by contributors(forked ones), including their individual commits.

There are 3 cases 

- [ ] User forked a repo, and working on a branch and pushing commits to forked repo without creating a PR, does that need to be displayed on Feed?
- [ ] After creating a PR, user is pushing commits to the branch(upon review) to the forked repo, that need to be displayed on Feed?
- [x] Merged commit (by a team member) displayed on Feed
Is this the task to be done? @rithviknishad

**Comment by rajku-dev** [comment]
@rithviknishad I have designed an algo that allows contributions made from forked repos to be displayed on feed,
Final Result looks like this
![Image](https://github.com/user-attachments/assets/43361109-d18a-4330-b614-2a9a70ceddb8)

Can i make a PR and work further on optimizing it?

**Comment by rithviknishad** [comment]
issue is about tracking commits in the data repo and not the feed page.

**Comment by rajku-dev** [comment]
> issue is about tracking commits in the flat data repo and not the feed page.

so we need to have this algo in a scraper in github-scraper folder (fetchForkedCommits.ts) and a new ACTIVITY_TYPE "forked_commits", with new  `commits : Activity[]` field in `ActivityData` 
changes will be reflected in .json file of users in data-repo and we can update profile from there on right? 
@rithviknishad

**Comment by rithviknishad** [comment]
why do we need a new activity type called "forked_commits"?

We should be tracking all types of commits via activity type: "pushed_commits" which includes forked or non forked ones

**Comment by rajku-dev** [comment]
> why do we need a new activity type called "forked_commits"?
> 
> We should be tracking all types of commits via activity type: "pushed_commits" which includes forked or non forked ones

exactly what i was thinking,
 we can have a new `forkedCommits` ACTIVITY_TYPE for `pushEvents` type of `Activity`
currently we are not parsing `pushEvents` in [parseEvents](https://github.com/ohcnetwork/leaderboard/blob/46eda0a118a2f084727bfafb2249c5ade02dd9f3/scraper/src/github-scraper/parseEvents.ts#L149), if we do we'll get `forkedCommits` type of `Activity` for core-team members, because this is what [fetchEvents](https://github.com/ohcnetwork/leaderboard/blob/46eda0a118a2f084727bfafb2249c5ade02dd9f3/scraper/src/github-scraper/fetchEvents.ts#L14s) fetches.
we'll write algo for fetching pushEvents from forked repos, and push it in existing `Activity[]` for users and sort them, or do we really need to sort them? may be because that scraper will push on top of existing Activities (Comment, Issue..) from existing scrapers.

**Comment by rithviknishad** [comment]
yup, sounds good. and skip sorting. this is just a dump of data. if sorting is needed ever for any situation, it should be happening during the pre-build step when data from json is loaded for building the pages

**Comment by rajku-dev** [comment]
> yup, sounds good. and skip sorting. this is just a dump of data. if sorting is needed ever for any situation, it should be happening during the pre-build step when data from json is loaded for building the pages

We can definitely do that. Could you please assign this issue to me? I’d like to move forward with implementing the discussed approach.

**Comment by rajku-dev** [comment]
How to observe the changes made in scrapers in local data-repo?  (.json file of users)
stumbled upon this [thread](https://rebuildearth.slack.com/archives/C06Q0HUAETE/p1710696732554309) for some guidance, set the `GIT_ACCESS_TOKEN` to `GIT_PAT` in secret,
got this [error](https://github.com/rajku-dev/leaderboard-data/actions/runs/12683837905/job/35351548534) while running the `leaderboard-data` workflow manually thorough GitHub interface

**Comment by rithviknishad** [comment]
> How to test the changes made by adding new scraper in local data repo? (.json file of users) stumbled upon this [thread](https://rebuildearth.slack.com/archives/C06Q0HUAETE/p1711550414812089?thread_ts=1710696732.554309&cid=C06Q0HUAETE) for some guidance, set the `GIT_ACCESS_TOKEN` to `GIT_PAT` in secret, got this [error](https://github.com/rajku-dev/leaderboard-data/actions/runs/12683837905/job/35351548534) while running the [`leaderboard-data`](https://github.com/ohcnetwork/leaderboard-data) workflow manually through GitHub interface Are we even allowed to do that or just write the code?

Just saw this. I believe you were able to figure out since you've already made the PR.

**Comment by rajku-dev** [comment]
> > How to test the changes made by adding new scraper in local data repo? (.json file of users) stumbled upon this [thread](https://rebuildearth.slack.com/archives/C06Q0HUAETE/p1711550414812089?thread_ts=1710696732.554309&cid=C06Q0HUAETE) for some guidance, set the `GIT_ACCESS_TOKEN` to `GIT_PAT` in secret, got this [error](https://github.com/rajku-dev/leaderboard-data/actions/runs/12683837905/job/35351548534) while running the [`leaderboard-data`](https://github.com/ohcnetwork/leaderboard-data) workflow manually through GitHub interface Are we even allowed to do that or just write the code?
> 
> Just saw this. I believe you were able to figure out since you've already made the PR.

not really, i tried deploying to vercel following the [docs](https://github.com/ohcnetwork/leaderboard-data-test#), but it [failed](https://vercel.com/new/clone?repository-url=https://github.com/coronasafe/leaderboard-org-data-template/tree/main&env=GITHUB_PAT&envDescription=GitHub+Personal+Access+Token+is+required+with+the+following+scopes+repo,+read:org,+read:project,+read:user&envLink=https://github.com/coronasafe/leaderboard-org-data-template/blob/main/README.md&project-name=leaderboard&repository-name=leaderboard-data&demo-title=Open+Healthcare+Network+-+Leaderboard&demo-description=Leaderboard+collects+data+from+GitHub+and+Slack+to+show+off+the+work+of+our+open+source+contributors&demo-url=https://contributors.ohc.network&demo-image=https://github.com/coronasafe/leaderboard/assets/25143503/6352a4cf-4b8b-4f80-b45c-6af323ee502e&root-directory=leaderboard&build-command=pnpm+build&install-command=./pre-deploy.sh+%26%26+pnpm+install&teamSlug=rajs-projects-fd23d08d&deploymentIds=dpl_4yBuQNMGKdpa1zgXpCZc17AbcegF&filter=errors)
i just need to test the scrapers which i have not figured out how.

**Comment by rajku-dev** [comment]
> you can test the scraper in your local.
> 
> first you'll need to pre-load any existing data-repo (you can start from scratch too if you want). run this: https://github.com/ohcnetwork/leaderboard/blob/main/package.json#L12
> 
> second, you can `cd` into the scraper directory and run the scraper by running the following command (assuming you have `gh` cli, or else replace with your own personal PAT token. No extra permissions to be configured. Any PAT works.
> 
> ```
> GITHUB_TOKEN=$(gh auth token) pnpm dev ohcnetwork ../data-repo/data/github
> ```

Thank You Sir, now i am able to test the scraper and debug the changes in terminal 🚀

**Comment by rithviknishad** [comment]
feel free to make a PR to update the README 😄

**Comment by rajku-dev** [comment]
> feel free to make a PR to update the README 😄

yeah that'd be better 🙂

**Comment by rithviknishad** [comment]
leaderboard has been re-built, this is no longer valid. thanks for putting in efforts in trying to achieve to solve this!

github scraper has been moved out, and the new scraper is partially capable of performing the same:

https://github.com/ohcnetwork/leaderboard-github-scraper
