### ISSUE TITLE
Enhancements to Slack Activities Bot

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/leaderboard#440]
### Enter your suggestions in details:

- [x] Move EOD Post workflow to GitHub Actions instead of Vercel Functions for a higher time-limit.
- [x] Ignore posting updates to the EOD channel for contributors without activity.
- [x] #442
- [x] #446
- [x] #447
- [ ] Send custom messages for no activity for 3+ days, 7+ days & 14+ days to contributor.
- [ ] Push to eod updates to data repo post the EOD messages sent to slack channel.
- [x] #449
- [ ] #451
- [ ] Change activity points scale to be similar to what we have in leaderboard ranking
- [x] #455
